//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Grade", ReplyAction="*")]
        WebApplication3.ServiceReference1.GradeResponse Grade(WebApplication3.ServiceReference1.GradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Grade", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.GradeResponse> GradeAsync(WebApplication3.ServiceReference1.GradeRequest request);
        
        // CODEGEN: Generating message contract since element name Date_TimeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Date_Time", ReplyAction="*")]
        WebApplication3.ServiceReference1.Date_TimeResponse Date_Time(WebApplication3.ServiceReference1.Date_TimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Date_Time", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.Date_TimeResponse> Date_TimeAsync(WebApplication3.ServiceReference1.Date_TimeRequest request);
        
        // CODEGEN: Generating message contract since element name PrintElementsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintElements", ReplyAction="*")]
        WebApplication3.ServiceReference1.PrintElementsResponse PrintElements(WebApplication3.ServiceReference1.PrintElementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintElements", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.PrintElementsResponse> PrintElementsAsync(WebApplication3.ServiceReference1.PrintElementsRequest request);
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Convertinatoru", ReplyAction="*")]
        WebApplication3.ServiceReference1.ConvertinatoruResponse Convertinatoru(WebApplication3.ServiceReference1.ConvertinatoruRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Convertinatoru", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.ConvertinatoruResponse> ConvertinatoruAsync(WebApplication3.ServiceReference1.ConvertinatoruRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GradeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Grade", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.GradeRequestBody Body;
        
        public GradeRequest() {
        }
        
        public GradeRequest(WebApplication3.ServiceReference1.GradeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GradeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double val;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        public GradeRequestBody() {
        }
        
        public GradeRequestBody(double val, string valuta) {
            this.val = val;
            this.valuta = valuta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GradeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GradeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.GradeResponseBody Body;
        
        public GradeResponse() {
        }
        
        public GradeResponse(WebApplication3.ServiceReference1.GradeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GradeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GradeResult;
        
        public GradeResponseBody() {
        }
        
        public GradeResponseBody(double GradeResult) {
            this.GradeResult = GradeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Date_TimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Date_Time", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.Date_TimeRequestBody Body;
        
        public Date_TimeRequest() {
        }
        
        public Date_TimeRequest(WebApplication3.ServiceReference1.Date_TimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Date_TimeRequestBody {
        
        public Date_TimeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Date_TimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Date_TimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.Date_TimeResponseBody Body;
        
        public Date_TimeResponse() {
        }
        
        public Date_TimeResponse(WebApplication3.ServiceReference1.Date_TimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Date_TimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Date_TimeResult;
        
        public Date_TimeResponseBody() {
        }
        
        public Date_TimeResponseBody(string Date_TimeResult) {
            this.Date_TimeResult = Date_TimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintElementsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintElements", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.PrintElementsRequestBody Body;
        
        public PrintElementsRequest() {
        }
        
        public PrintElementsRequest(WebApplication3.ServiceReference1.PrintElementsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PrintElementsRequestBody {
        
        public PrintElementsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintElementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintElementsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.PrintElementsResponseBody Body;
        
        public PrintElementsResponse() {
        }
        
        public PrintElementsResponse(WebApplication3.ServiceReference1.PrintElementsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintElementsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication3.ServiceReference1.ArrayOfString PrintElementsResult;
        
        public PrintElementsResponseBody() {
        }
        
        public PrintElementsResponseBody(WebApplication3.ServiceReference1.ArrayOfString PrintElementsResult) {
            this.PrintElementsResult = PrintElementsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertinatoruRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Convertinatoru", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.ConvertinatoruRequestBody Body;
        
        public ConvertinatoruRequest() {
        }
        
        public ConvertinatoruRequest(WebApplication3.ServiceReference1.ConvertinatoruRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertinatoruRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double val;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        public ConvertinatoruRequestBody() {
        }
        
        public ConvertinatoruRequestBody(double val, string valuta) {
            this.val = val;
            this.valuta = valuta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertinatoruResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertinatoruResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.ConvertinatoruResponseBody Body;
        
        public ConvertinatoruResponse() {
        }
        
        public ConvertinatoruResponse(WebApplication3.ServiceReference1.ConvertinatoruResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertinatoruResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ConvertinatoruResult;
        
        public ConvertinatoruResponseBody() {
        }
        
        public ConvertinatoruResponseBody(double ConvertinatoruResult) {
            this.ConvertinatoruResult = ConvertinatoruResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication3.ServiceReference1.WebService1Soap>, WebApplication3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference1.GradeResponse WebApplication3.ServiceReference1.WebService1Soap.Grade(WebApplication3.ServiceReference1.GradeRequest request) {
            return base.Channel.Grade(request);
        }
        
        public double Grade(double val, string valuta) {
            WebApplication3.ServiceReference1.GradeRequest inValue = new WebApplication3.ServiceReference1.GradeRequest();
            inValue.Body = new WebApplication3.ServiceReference1.GradeRequestBody();
            inValue.Body.val = val;
            inValue.Body.valuta = valuta;
            WebApplication3.ServiceReference1.GradeResponse retVal = ((WebApplication3.ServiceReference1.WebService1Soap)(this)).Grade(inValue);
            return retVal.Body.GradeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.GradeResponse> WebApplication3.ServiceReference1.WebService1Soap.GradeAsync(WebApplication3.ServiceReference1.GradeRequest request) {
            return base.Channel.GradeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference1.GradeResponse> GradeAsync(double val, string valuta) {
            WebApplication3.ServiceReference1.GradeRequest inValue = new WebApplication3.ServiceReference1.GradeRequest();
            inValue.Body = new WebApplication3.ServiceReference1.GradeRequestBody();
            inValue.Body.val = val;
            inValue.Body.valuta = valuta;
            return ((WebApplication3.ServiceReference1.WebService1Soap)(this)).GradeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference1.Date_TimeResponse WebApplication3.ServiceReference1.WebService1Soap.Date_Time(WebApplication3.ServiceReference1.Date_TimeRequest request) {
            return base.Channel.Date_Time(request);
        }
        
        public string Date_Time() {
            WebApplication3.ServiceReference1.Date_TimeRequest inValue = new WebApplication3.ServiceReference1.Date_TimeRequest();
            inValue.Body = new WebApplication3.ServiceReference1.Date_TimeRequestBody();
            WebApplication3.ServiceReference1.Date_TimeResponse retVal = ((WebApplication3.ServiceReference1.WebService1Soap)(this)).Date_Time(inValue);
            return retVal.Body.Date_TimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.Date_TimeResponse> WebApplication3.ServiceReference1.WebService1Soap.Date_TimeAsync(WebApplication3.ServiceReference1.Date_TimeRequest request) {
            return base.Channel.Date_TimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference1.Date_TimeResponse> Date_TimeAsync() {
            WebApplication3.ServiceReference1.Date_TimeRequest inValue = new WebApplication3.ServiceReference1.Date_TimeRequest();
            inValue.Body = new WebApplication3.ServiceReference1.Date_TimeRequestBody();
            return ((WebApplication3.ServiceReference1.WebService1Soap)(this)).Date_TimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference1.PrintElementsResponse WebApplication3.ServiceReference1.WebService1Soap.PrintElements(WebApplication3.ServiceReference1.PrintElementsRequest request) {
            return base.Channel.PrintElements(request);
        }
        
        public WebApplication3.ServiceReference1.ArrayOfString PrintElements() {
            WebApplication3.ServiceReference1.PrintElementsRequest inValue = new WebApplication3.ServiceReference1.PrintElementsRequest();
            inValue.Body = new WebApplication3.ServiceReference1.PrintElementsRequestBody();
            WebApplication3.ServiceReference1.PrintElementsResponse retVal = ((WebApplication3.ServiceReference1.WebService1Soap)(this)).PrintElements(inValue);
            return retVal.Body.PrintElementsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.PrintElementsResponse> WebApplication3.ServiceReference1.WebService1Soap.PrintElementsAsync(WebApplication3.ServiceReference1.PrintElementsRequest request) {
            return base.Channel.PrintElementsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference1.PrintElementsResponse> PrintElementsAsync() {
            WebApplication3.ServiceReference1.PrintElementsRequest inValue = new WebApplication3.ServiceReference1.PrintElementsRequest();
            inValue.Body = new WebApplication3.ServiceReference1.PrintElementsRequestBody();
            return ((WebApplication3.ServiceReference1.WebService1Soap)(this)).PrintElementsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference1.ConvertinatoruResponse WebApplication3.ServiceReference1.WebService1Soap.Convertinatoru(WebApplication3.ServiceReference1.ConvertinatoruRequest request) {
            return base.Channel.Convertinatoru(request);
        }
        
        public double Convertinatoru(double val, string valuta) {
            WebApplication3.ServiceReference1.ConvertinatoruRequest inValue = new WebApplication3.ServiceReference1.ConvertinatoruRequest();
            inValue.Body = new WebApplication3.ServiceReference1.ConvertinatoruRequestBody();
            inValue.Body.val = val;
            inValue.Body.valuta = valuta;
            WebApplication3.ServiceReference1.ConvertinatoruResponse retVal = ((WebApplication3.ServiceReference1.WebService1Soap)(this)).Convertinatoru(inValue);
            return retVal.Body.ConvertinatoruResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.ConvertinatoruResponse> WebApplication3.ServiceReference1.WebService1Soap.ConvertinatoruAsync(WebApplication3.ServiceReference1.ConvertinatoruRequest request) {
            return base.Channel.ConvertinatoruAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference1.ConvertinatoruResponse> ConvertinatoruAsync(double val, string valuta) {
            WebApplication3.ServiceReference1.ConvertinatoruRequest inValue = new WebApplication3.ServiceReference1.ConvertinatoruRequest();
            inValue.Body = new WebApplication3.ServiceReference1.ConvertinatoruRequestBody();
            inValue.Body.val = val;
            inValue.Body.valuta = valuta;
            return ((WebApplication3.ServiceReference1.WebService1Soap)(this)).ConvertinatoruAsync(inValue);
        }
    }
}
